import { motion } from 'framer-motion';

export default function TermsOfService() {
    return (
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
            <motion.div
                initial={{ opacity: 0, scale: 0.98, y: 20 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                className="bg-[#fafafa] text-slate-800 rounded-sm shadow-[0_25px_50px_-12px_rgba(0,0,0,0.5)] p-10 md:p-16 relative mx-auto"
                style={{
                    backgroundImage: 'radial-gradient(#e5e7eb 1px, transparent 1px)',
                    backgroundSize: '24px 24px'
                }}
            >
                <div className="absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r from-violet-500 to-fuchsia-500"></div>

                <div className="mb-12 border-b border-slate-300 pb-8">
                    <h1 className="text-4xl md:text-5xl font-extrabold text-slate-900 mb-3 font-serif">Terms of Service</h1>
                    <p className="text-slate-500 font-mono text-sm uppercase tracking-widest">Last updated: April 21, 2026</p>
                </div>

                <div className="space-y-8 prose prose-slate max-w-none prose-headings:text-slate-900 prose-headings:font-serif prose-a:text-fuchsia-600 prose-p:leading-relaxed">
                    <section>
                        <h2 className="text-2xl font-bold mb-4">1. Agreement to Terms</h2>
                        <p>
                            By accessing or using MeshVista ("the Platform"), you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4">2. Description of Service</h2>
                        <p>
                            MeshVista provides AI-powered tools that convert 2D images into 3D models. We also offer a marketplace where users can publish, buy, and sell generated 3D models.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4">3. User Accounts</h2>
                        <p>
                            You must create an account to use certain features. You are responsible for safeguarding your password and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4">4. Intellectual Property & Generations</h2>
                        <p>
                            When you upload an image, you must have the legal right to use that image. The resulting 3D models generated by MeshVista using your images belong to you. We claim no ownership over your inputs or outputs, except a limited license to store, display, and process them to provide our service.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4">5. Marketplace Rules</h2>
                        <p>
                            If you choose to sell models on our marketplace:
                        </p>
                        <ul className="list-disc pl-5 mt-2 space-y-2">
                            <li>You ensure the content does not violate any third-party copyrights or trademarks.</li>
                            <li>We retain a 30% commission on all sales. You receive 70% of the sale price.</li>
                            <li>We reserve the right to remove any listing at our discretion if it violates our acceptable use policy.</li>
                        </ul>
                    </section>
                </div>
            </motion.div>
        </div>
    );
}
